### ISSUE TITLE
[Linux] Can't display terrain, networks and elevation

### ISSUE THREAD

**Issue by adamkoss** [Marginal/OverlayEditor#2]
Version: 2.52

Windows (via WINE, correct):
![with_terrain](https://cloud.githubusercontent.com/assets/19344568/17272010/a5f765ba-568b-11e6-8c0c-afc5361f303e.png)

Linux (Arch Linux, not correct; python 2.7.12, python2-numpy 1.11.1, wxpython 3.0.2, python2-pillow 3.3.0):
![no_terrain](https://cloud.githubusercontent.com/assets/19344568/17272009/a5f69482-568b-11e6-86b4-a0b67d017f9d.png)

**Comment by Marginal** [comment]
Install the p7zip package.
Also, if you want GeoTIFF or georeferenced JPEG2000 background images, install the gdal package.

**Comment by adamkoss** [comment]
``` sh
$ pacman -Q p7zip gdal
p7zip 16.02-1
gdal 2.1.0-2
```

I've got both packages and still doesn't work :disappointed:
`gdal` package also contains python2 libs.

**Comment by Marginal** [comment]
Any error messages in the terminal when you restart and visit this place?

**Comment by adamkoss** [comment]
Attached console output (open scenery package, set 'no terrain' ('show terrain and networks' option is default), and 'show terrain and networks' again):

[stderr.txt](https://github.com/Marginal/OverlayEditor/files/392534/stderr.txt)
[stdout.txt](https://github.com/Marginal/OverlayEditor/files/392533/stdout.txt)

**Comment by Marginal** [comment]
Thanks. I can reproduce with python2-numpy 1.11.0 on Ubuntu. Appears to be [this issue](https://github.com/numpy/numpy/issues/6464).

**Comment by adamkoss** [comment]
Thanks :smile:
