### ISSUE TITLE
Can't add hole-polygon to AGS polygon

### ISSUE THREAD

**Issue by adamkoss** [Marginal/OverlayEditor#3]
I can't add hole in AGS (Autogen String) polygon, however it is possible, according x-plane documentation. I attach screenshot from this documentation (I had to reduce table, because it is very long...). 
![screenshot_20160810_120255](https://cloud.githubusercontent.com/assets/19344568/17550162/e8892812-5ef3-11e6-86e6-2018b1a7dc03.png)

**Comment by Marginal** [comment]
Should be fairly easy to add.
What's a good default for the "parameter" for new AutoGen string placements: 257 = 1 side, 4m height?
Similarly for AutoGen Block placements: 256 = Spelling 0, 4m height?

**Comment by Marginal** [comment]
Please let me know how you get on.
FYI turns out that "Number of Active Sides" <= number of windings (or 1 + number of holes).

**Comment by adamkoss** [comment]
In default DSF files, AGS parameter = 257 and AGB = 263 or 259, but I don't know why. When I declare 257 for AGS and 263 for AGB (in decompiled DSF file), result was OK.

**Comment by adamkoss** [comment]
Program works correct, thanks :)

**Comment by Marginal** [comment]
AutoGen Strings don't have to be "simple" and aren't "closed" in the conventional sense like Draped polygons, Forests or AutoGen Blocks. They're more like Strings so ccd0cd9 + 25b26e5 display them as open and don't do anything special if they're non-simple.

But I can't get a handle on how additional windings ("holes") are supposed to work. The [documentation](http://developer.x-plane.com/?article=autogen-string-ags-file-format-specification) says "every winding is fully closed (two adjacent windings share and duplicate a vertex)", which suggests that I ought to glue the first node of a new winding to the location of the last node of the previous winding. And in practice adding additional windings that aren't joined on to the previous winding produces weird results. But in that case, what's the point of additional windings? Have you found a use for them?

**Comment by adamkoss** [comment]
I suppose, that additional winding is a hole-polygon. In AGS polygon (base polygon), node 0 and last node is not connected and buildings are not spawned there. This gap has to be stuck with hole-polygon. First node of outer winding (base polygon) has to be duplicated with last node of hole-polygon and vice versa. Other nodes of hole-polygon you should shape for the sake of your expectation. If you want to create buildings on first, second and third sides, you should shape hole-polygon like that: 
![screenshot_20160810_205714](https://cloud.githubusercontent.com/assets/19344568/17567275/f71d1956-5f3e-11e6-8ad1-aac0d7ea51c4.png)
If only on two sides:
![screenshot_20160810_205855](https://cloud.githubusercontent.com/assets/19344568/17567280/fa314252-5f3e-11e6-875b-8a3a9f323301.png)

**Comment by Marginal** [comment]
> node 0 and last node is not connected and buildings are not spawned there. This gap has to be stuck with hole-polygon.

Yes, AutoGen Strings appear to be "open" - the segment between the last node and node 0 is not populated with buildings. But one can easily close the "gap" by just adding an additional node (node 4 in this example) and placing it in the same location as node 0.

> If you want to create buildings on first, second and third sides, you should shape hole-polygon like that

Again, I don't see how a hole adds anything; the same effect can be achieved more easily by adding nodes in the desired shape and adding a final node (node 8 in this example) in the same location as node 0.

**Comment by adamkoss** [comment]
If you duplicate first and last node of the same winding, buildings will be created on all sides. The attached picture presents it (how can I change value in red outline?):
![screenshot_20160811_104103](https://cloud.githubusercontent.com/assets/19344568/17583589/f4fae0a4-5fb1-11e6-9d75-3acc2c9d1209.png)

**Comment by Marginal** [comment]
> how can I change value in red outline?

Since you don't have any "holes" the only useful value is 1; 0 will cause the entire thing to disappear and >=2 will cause X-Plane to give an error.
If you add one or more holes you can then adjust the number of sides with Shift + R and F.

**Comment by adamkoss** [comment]
OK, thanks ;)
